--
-- PostgreSQL database cluster dump
--

-- Started on 2026-04-26 22:23:53 MSK

\restrict fgFbrs4bmiBc79axTNuvjIvsMVCaDlqaeOKlVNbcBFclNDZKNS6lhu2sZhsBQQ6

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS;

--
-- User Configurations
--








\unrestrict fgFbrs4bmiBc79axTNuvjIvsMVCaDlqaeOKlVNbcBFclNDZKNS6lhu2sZhsBQQ6

--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

\restrict FeQUvi3z0m86PoRb4aCgXjK7gJRZ1qWN5PW6Oc2WuQG5sK7BhEUHwcB2VSRBqu5

-- Dumped from database version 18.1 (Debian 18.1-1.pgdg13+2)
-- Dumped by pg_dump version 18.3

-- Started on 2026-04-26 22:23:53 MSK

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Completed on 2026-04-26 22:23:53 MSK

--
-- PostgreSQL database dump complete
--

\unrestrict FeQUvi3z0m86PoRb4aCgXjK7gJRZ1qWN5PW6Oc2WuQG5sK7BhEUHwcB2VSRBqu5

--
-- Database "doomb" dump
--

--
-- PostgreSQL database dump
--

\restrict stP2spWeaGVuC9CMiFTamvBkhcNFJXa2Ha2anzFj6RlHUM0YgFQYZyItKOogBEx

-- Dumped from database version 18.1 (Debian 18.1-1.pgdg13+2)
-- Dumped by pg_dump version 18.3

-- Started on 2026-04-26 22:23:53 MSK

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3467 (class 1262 OID 16384)
-- Name: doomb; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE doomb WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE doomb OWNER TO postgres;

\unrestrict stP2spWeaGVuC9CMiFTamvBkhcNFJXa2Ha2anzFj6RlHUM0YgFQYZyItKOogBEx
\connect doomb
\restrict stP2spWeaGVuC9CMiFTamvBkhcNFJXa2Ha2anzFj6RlHUM0YgFQYZyItKOogBEx

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16390)
-- Name: stats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stats (
    stat_id integer NOT NULL,
    date timestamp with time zone,
    user_id integer,
    is_correct boolean NOT NULL,
    task_id integer NOT NULL
);


ALTER TABLE public.stats OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: stats_stat_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.stats ALTER COLUMN stat_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stats_stat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 24612)
-- Name: tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks (
    task_id integer NOT NULL,
    task_name character varying NOT NULL,
    task_text text,
    correct_answer text
);


ALTER TABLE public.tasks OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 24611)
-- Name: tasks_task_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks ALTER COLUMN task_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tasks_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16399)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    login character varying NOT NULL,
    password character varying NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16398)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3457 (class 0 OID 16390)
-- Dependencies: 220
-- Data for Name: stats; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.stats (stat_id, date, user_id, is_correct, task_id) FROM stdin;
10	2026-04-26 14:46:49.795+00	14	t	2
11	2026-04-26 14:46:55.895+00	14	f	2
\.


--
-- TOC entry 3461 (class 0 OID 24612)
-- Dependencies: 224
-- Data for Name: tasks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks (task_id, task_name, task_text, correct_answer) FROM stdin;
1	findNodesByDepth	\nASCII-схема:\na --> b --> d\n|     |     |\nv     v     v\nc --> e --> f\n\nРёбра:\na->b, a->c, b->d, b->e\nc->e, c->f, d->f, e->f\n\nВопрос:\nИз a найти вершины, достижимые ровно за 2 шага.\n	d,e,f
2	findNodesByDepth	\nASCII-схема:\ns --> a --> c\n|     |     |\nv     v     v\nb --> d --> e\n\nРёбра:\ns->a, s->b, a->c, a->d\nb->d, c->e, d->e\n\nВопрос:\nИз s найти вершины, достижимые ровно за 2 шага.\n	c,d
3	findNodesByDepth	\nASCII-схема:\np --> q --> s\n|     |     ^\nv     v    /\nr --> t --> u\n\nРёбра:\np->q, p->r, q->s, q->t\nr->t, t->u, u->s\n\nВопрос:\nИз p найти вершины, достижимые ровно за 2 шага.\n	s,t
4	findNodesByDepth	\nASCII-схема:\nm --> n --> p\n|     |     |\nv     v     v\no --> q --> r\n\nРёбра:\nm->n, m->o, n->p, n->q\no->q, q->r, p->r\n\nВопрос:\nИз m найти вершины, достижимые ровно за 2 шага.\n	p,q
5	findNodesByDepth	\nASCII-схема:\nx --> y --> w --> u\n|     |     /\nv     v    /\nz --> t --/\n\nРёбра:\nx->y, x->z, y->w, y->t\nz->t, t->u, w->u\n\nВопрос:\nИз x найти вершины, достижимые ровно за 2 шага.\n	t,w
6	isPathShortest	\nASCII-схема:\na --> b --> d\n \\         ^\n  \\-> c ---/\n\nРёбра:\na->b, b->d, a->c, c->d\n\nПуть:\na->b->d\n\nВопрос:\nЯвляется ли путь кратчайшим от a до d?\n	да
7	isPathShortest	\nASCII-схема:\ns --> a --> b --> t\n \\             ^\n  \\-> c ------/\n\nРёбра:\ns->a, a->b, b->t, s->c\nc->t, a->t\n\nПуть:\ns->a->b->t\n\nВопрос:\nЯвляется ли путь кратчайшим от s до t?\n	нет
8	isPathShortest	\nASCII-схема:\np --> q --> r --> t\n \\         ^\n  \\-> s ---/\n\nРёбра:\np->q, q->r, p->s, s->r\nr->t\n\nПуть:\np->s->r\n\nВопрос:\nЯвляется ли путь кратчайшим от p до r?\n	да
9	isPathShortest	\nASCII-схема:\nm --> n --> o --> p\n \\         ^\n  \\-> q ---/\n\nРёбра:\nm->n, n->o, o->p, m->q\nq->p, n->p\n\nПуть:\nm->n->o->p\n\nВопрос:\nЯвляется ли путь кратчайшим от m до p?\n	нет
10	isPathShortest	\nASCII-схема:\nx --> y --> z --> u\n \\         ^\n  \\-> w ---/\n\nРёбра:\nx->y, y->z, x->w, w->z\nz->u\n\nПуть:\nx->w->z\n\nВопрос:\nЯвляется ли путь кратчайшим от x до z?\n	да
11	primesAlgorithm	\nASCII-схема:\na --2-- b\n| \\     |\n3  5    6\n|  \\    |\nd --1-- c\n\nРёбра:\na-b(2), a-c(5), a-d(3)\nb-c(4), b-d(6), c-d(1)\n\nСтарт:\na\n\nВопрос:\nКакое ребро выберет Прим первым?\n	a-b
12	primesAlgorithm	\nASCII-схема:\ns --7-- a\n| \\     |\n2  4    3\n|  \\    |\nb --6-- c\n\nРёбра:\ns-a(7), s-b(2), s-c(4)\na-b(3), a-c(5), b-c(6)\n\nСтарт:\ns\n\nВопрос:\nКакое ребро выберет Прим первым?\n	s-b
13	primesAlgorithm	\nASCII-схема:\np --8-- q\n| \\     |\n1  4    2\n|  \\    |\nr --3-- s\n\nРёбра:\np-q(8), p-r(1), p-s(4)\nq-r(2), q-s(7), r-s(3)\n\nСтарт:\np\n\nВопрос:\nКакое ребро выберет Прим первым?\n	p-r
14	primesAlgorithm	\nASCII-схема:\nm --6-- n\n| \\     |\n2  5    3\n|  \\    |\no --4-- p\n\nРёбра:\nm-n(6), m-o(2), m-p(5)\nn-o(3), n-p(7), o-p(4)\n\nСтарт:\nm\n\nВопрос:\nКакое ребро выберет Прим первым?\n	m-o
15	primesAlgorithm	\nASCII-схема:\nx --9-- y\n| \\     |\n3  8    4\n|  \\    |\nz --5-- w\n\nРёбра:\nx-y(9), x-z(3), x-w(8)\ny-z(4), y-w(6), z-w(5)\n\nСтарт:\nx\n\nВопрос:\nКакое ребро выберет Прим первым?\n	x-z
16	kruskalsAlgorithm	\nASCII-схема:\na --1-- b --2-- c --3-- d\n \\      / \\      /\n 4    5   6    7\n\nРёбра:\na-b(1), b-c(2), c-d(3)\na-d(4), a-c(5), b-d(6)\n\nУже выбраны:\na-b, b-c\n\nВопрос:\nКакое следующее ребро выберет Краскал?\n	c-d
17	kruskalsAlgorithm	\nASCII-схема:\ns --1-- t --2-- u --3-- v\n \\      / \\      /\n 4    5   6    7\n\nРёбра:\ns-t(1), t-u(2), u-v(3)\ns-v(4), s-u(5), t-v(6)\n\nУже выбраны:\ns-t, t-u\n\nВопрос:\nКакое следующее ребро выберет Краскал?\n	u-v
18	kruskalsAlgorithm	\nASCII-схема:\np --1-- q --2-- r --3-- s\n \\      / \\      /\n 4    5   6    7\n\nРёбра:\np-q(1), q-r(2), r-s(3)\np-s(4), p-r(5), q-s(6)\n\nУже выбраны:\np-q\n\nВопрос:\nКакое следующее ребро выберет Краскал?\n	q-r
19	kruskalsAlgorithm	\nASCII-схема:\nm --2-- n --3-- o --4-- p\n \\      / \\      /\n 5    6   7    8\n\nРёбра:\nm-n(2), n-o(3), o-p(4)\nm-p(5), m-o(6), n-p(7)\n\nУже выбраны:\nm-n, n-o\n\nВопрос:\nКакое следующее ребро выберет Краскал?\n	o-p
20	kruskalsAlgorithm	\nASCII-схема:\nx --1-- y --2-- z --3-- w\n \\      / \\      /\n 4    5   6    7\n\nРёбра:\nx-y(1), y-z(2), z-w(3)\nx-w(4), x-z(5), y-w(6)\n\nУже выбраны:\nx-y, y-z\n\nВопрос:\nКакое следующее ребро выберет Краскал?\n	z-w
\.


--
-- TOC entry 3459 (class 0 OID 16399)
-- Dependencies: 222
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (user_id, login, password) FROM stdin;
1	user	123
2	user2	123
3	user3	123
4	user44	123
5	user5	1
6	user34	123
7	use2	12
8	u	1
9	j	1
10	lll	mmm
11	user14	123
12	user45	123
13	u4	123
14	testuser2	testpass
\.


--
-- TOC entry 3468 (class 0 OID 0)
-- Dependencies: 219
-- Name: stats_stat_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.stats_stat_id_seq', 11, true);


--
-- TOC entry 3469 (class 0 OID 0)
-- Dependencies: 223
-- Name: tasks_task_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_task_id_seq', 20, true);


--
-- TOC entry 3470 (class 0 OID 0)
-- Dependencies: 221
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_id_seq', 14, true);


--
-- TOC entry 3300 (class 2606 OID 16397)
-- Name: stats stats_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stats
    ADD CONSTRAINT stats_pk PRIMARY KEY (stat_id);


--
-- TOC entry 3306 (class 2606 OID 24620)
-- Name: tasks tasks_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pk PRIMARY KEY (task_id);


--
-- TOC entry 3302 (class 2606 OID 16408)
-- Name: users users_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pk PRIMARY KEY (user_id);


--
-- TOC entry 3304 (class 2606 OID 16410)
-- Name: users users_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_unique UNIQUE (login);


--
-- TOC entry 3307 (class 2606 OID 24624)
-- Name: stats stats_tasks_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stats
    ADD CONSTRAINT stats_tasks_fk FOREIGN KEY (task_id) REFERENCES public.tasks(task_id);


--
-- TOC entry 3308 (class 2606 OID 16411)
-- Name: stats stats_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stats
    ADD CONSTRAINT stats_users_fk FOREIGN KEY (user_id) REFERENCES public.users(user_id);


-- Completed on 2026-04-26 22:23:54 MSK

--
-- PostgreSQL database dump complete
--

\unrestrict stP2spWeaGVuC9CMiFTamvBkhcNFJXa2Ha2anzFj6RlHUM0YgFQYZyItKOogBEx

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

\restrict 0Z5PXTeyzIfqGnuJgAcThdTaClDoWdaltrh9whYiBjQ5pI9vrOWCsnLY8ojqOpm

-- Dumped from database version 18.1 (Debian 18.1-1.pgdg13+2)
-- Dumped by pg_dump version 18.3

-- Started on 2026-04-26 22:23:54 MSK

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Completed on 2026-04-26 22:23:54 MSK

--
-- PostgreSQL database dump complete
--

\unrestrict 0Z5PXTeyzIfqGnuJgAcThdTaClDoWdaltrh9whYiBjQ5pI9vrOWCsnLY8ojqOpm

-- Completed on 2026-04-26 22:23:54 MSK

--
-- PostgreSQL database cluster dump complete
--

